apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcosidekick-ui
  namespace: falco
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: falco-falcosidekick-ui
            port:
              number: 2802
    host: sidekick.162.19.109.131.sslip.io
  tls:
  - hosts:
    - sidekick.162.19.109.131.sslip.io
    secretName: falcosidekick-ui-tls
