apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: falco-talon
  name: falco-talon-rules
  namespace: falco
data:
  rules.yaml: |
    - action: Terminate Pod
      actionner: kubernetes:terminate
      parameters:
        ignore_daemonsets: true
        ignore_statefulsets: true
        grace_period_seconds: 10

    - action: Disable outbound connections
      actionner: kubernetes:networkpolicy
      parameters:
        allow:
          - "192.168.1.0/24"
          - "172.17.0.0/16"
          - "10.0.0.0/32"

    - action: Labelize Pod as Suspicious
      actionner: kubernetes:labelize
      parameters:
        labels:
          suspicious: true

    #### rules #######
    - rule: zarb-01
      match:
        rules:
          - Terminal shell in container
      actions:
        - action: Labelize Pod as Suspicious

    - rule: zarb-02
      match:
        rules:
          - Try to use cowsay in a container
        output_fields:
          - k8s.ns.name!=kube-system, k8s.ns.name!=falco
      actions:
        - action: Labelize Pod as Suspicious
        - action: Disable outbound connections
        - action: Terminate Pod
